export const PLACEHOLDER_ID = -1;
export const PLACEHOLDER_DATE = new Date(1);
export const MAX_INT_4 = 2147483648;

// error messages
export const USERNAME_OR_PASSWORD_IS_NOT_VALID =
  'USERNAME_OR_PASSWORD_IS_NOT_VALID';
export const REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND';
export const POST_NOT_FOUND = 'POST_NOT_FOUND';
export const POST_LANGUAGE_AND_TITLE_MUST_BE_UNIQUE =
  'POST_LANGUAGE_AND_TITLE_MUST_BE_UNIQUE';
