version: '3.8'

services:
  portfolio-db:
    image: postgres:alpine
    hostname: portfolio-db
    container_name: portfolio-db
    restart: no
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 10s
      timeout: 30s
      retries: 5

volumes:
  db_data:
    driver: local
